# -*- coding: utf-8 -*-
"""CS_PY_TODO.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZrH9-Y2tnss7GOm1YuIk0g9Ra-ieOtCz
"""

todo_list = []

while True:
    option = int(input("Enter \n 1. To add to list \n 2. Remove from list \n 3. View list \n 4. Mark done \n 5. Exit \n"))
    if(option == 1):
        print("Enter all elements and hit space and enter to exit \n")
        while True:
            user_input = input()
            if user_input == " ":
                break
            todo_list.append(user_input)

    elif(option == 2):
        while True:
            for i in range(len(todo_list)):
              print(f"{i+1}. {todo_list[i]}")
            del_input = int(input("Enter the index of element you want to remove and 0 for done \n"))
            if del_input == 0:
                break
            todo_list.pop(del_input - 1)


    elif(option == 3):
        for item in todo_list:
            print(item)

    elif(option == 4):
        done_input = int(input("Enter the index of element \n"))
        for i, element in enumerate(todo_list):
            if i == done_input -1:
                print(f"{element} (done)")
            else:
                print(element)

    elif(option == 5):
        break

    else:
        print("Option not found")