# -*- coding: utf-8 -*-
"""cs_py_simple_calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xIP_uG1pnRnOgUP0i3w860vwKznuY-Hz
"""

def calculator(num1 , num2 , operation):
    if operation == 1:
        print(f"Total : {num1 + num2}")

    elif operation == 2:
        print(f"Total : {num1 - num2}")

    elif operation == 3:
        print(f"Total : {num1 * num2}")

    elif operation == 4:
        print(f"Total : {format(num1 / num2 , '.4f')}")

    elif operation == 5:
        return

while True:
    operation = int(input("Enter \n 1 for add \n 2 for sub \n 3 for mul \n 4 for divide \n 5 for Exit" ))
    if operation == 5:
        break
    elif 4 >= operation and operation >=1:
        num1 = int(input("Enter 1st number:"))
        num2 = int(input("Enter 2nd number:"))
        calculator(num1,num2,operation)
    else:
        print("Wrong Input")